/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 laptop.glb 
Author: hellfa (https://sketchfab.com/hellfa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-d55ef30e28b1455bad46e0beeb85bfc6
Title: Laptop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/laptop.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.122, 40.245, -51.767]} rotation={[-0.554, 0, 0]} scale={[4.269, 5.129, 1]}>
        <mesh geometry={nodes['klapa_Material_#41_0'].geometry} material={materials.Material_41} position={[-11.875, -5.344, 0.108]} />
      </group>
      <mesh geometry={nodes['podstawa_Material_#28_0'].geometry} material={materials.Material_28} position={[-50.569, 1.532, 47.852]} rotation={[-Math.PI / 2, 0, 0]} scale={[4.269, 5.129, 1]} />
      <mesh geometry={nodes['Sphere002_Material_#42_0'].geometry} material={materials.Material_42} position={[61.864, 0.045, 62.738]} rotation={[Math.PI / 2, 0, 0]} scale={[0.931, 0.931, 0.284]} />
    </group>
  )
}

useGLTF.preload('/laptop.glb')
